### ISSUE TITLE
How this work?

### ISSUE THREAD

**Issue by ghost** [Him188/MyMap#1]

**Comment by Him188** [comment]
By using command /mapadmin ?... I've forgotten too...

**Comment by ghost** [comment]
I don't understand chinese...

So..

**Comment by Him188** [comment]
emmm... let me work on English version this month off. sorry fot that

**Comment by Him188** [comment]
the moth off is Dec.30 to Jan.1, think i can finish

**Comment by ghost** [comment]
ok thx so much

**Comment by Him188** [comment]
finished, thank you

**Comment by ghost** [comment]
Thanks so much for support! Love you! 

Happy new year!
