### ISSUE TITLE
Broken Download Link

### ISSUE THREAD

**Issue by ChickenSaysBak** [Him188/MyMap#13]
Hello, I am trying to download this plugin, but the link doesn't work:
http://mamoe.net:2333/viewType.html?buildTypeId=Mymap_Build

**Comment by Him188** [comment]
The server is down again...Please build it by yourself

**Comment by ChickenSaysBak** [comment]
I'm not entirely sure how to do that (a bit of a noob haha), yesterday I tried downloading the source, importing it into eclipse, and exporting it, but then it was unrecognized by /plugins and didn't have any errors in console.

**Comment by Him188** [comment]
Alright, I will build it and publish it to GitHub release.
Thanks for using this plugin!

**Comment by ChickenSaysBak** [comment]
Thank you so much!

**Comment by Him188** [comment]
[Here](https://github.com/Him188/MyMap/releases/tag/1.5) it is
