### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by ghost** [Him188/MyMap#2]
I can't compile them idk why.

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.216 s
[INFO] Finished at: 2018-01-20T00:05:44+02:00
[INFO] Final Memory: 6M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file (install-external) on project mymap: The parameters 'file' for goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file are missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException

Process finished with exit code 1

**Comment by ghost** [comment]
(Add support for java 8)

**Comment by ghost** [comment]
@Him188

**Comment by Him188** [comment]
sorry, i am at school now, i'll check it in 2 weeks

**Comment by Him188** [comment]
fixed
