### ISSUE TITLE
How setup?

### ISSUE THREAD

**Issue by ghost** [Him188/MyMap#3]
Lang it's chinese, you setup? :/

I don't understand how it's supposed create.

**Comment by XDqrkneZ** [comment]
help

**Comment by Him188** [comment]
@XDqrkneZ , Thank you,  I had added English support months ago. You can change language in config.yml. 
LanguageBase.java: [View Code](https://github.com/Him188/MyMap/blob/master/src/main/java/com/him188/mymap/utils/LanguageBase.java)
