### ISSUE TITLE
enlarge the image

### ISSUE THREAD

**Issue by MrReskill** [Him188/MyMap#7]
Hello,
How can I enlarge the image on 4x4 instead of putting it in a single frame

Thanks you.

**Comment by uselesswaifu** [comment]
https://mc-map.djfun.de/
This website is very useful

**Comment by Him188** [comment]
![tim 20180824134427](https://user-images.githubusercontent.com/12100985/44567189-da5f8100-a7a3-11e8-9d02-492ed7a2437a.png)
Do you mean this? Just follow the [Usage](https://github.com/Him188/MyMap#usage)

**Comment by Him188** [comment]
Emmm.. mayby you don't understand Chinese.. I am going to add Auto Language Select

**Comment by Him188** [comment]
Ok, you can set config `language` to `Auto` or `English`, then you will see English messages.

**Comment by MrReskill** [comment]
When we play every other time there is more and more times he can press to update the block

**Comment by Him188** [comment]
That's a bug... Bug i don't know how to fix

**Comment by MrReskill** [comment]
its fix ?

**Comment by Him188** [comment]
emm.. i cannot fix it. The block upating schedule is complected. i wrote lots of functions in the plugin to make the image displayed, overwise it will be difficult for player to see the image. i dont know how to improve updating methods, sorry

**Comment by Him188** [comment]
When i was testing today, i found it may be fixed.
