### ISSUE TITLE
Can't break item frames, what should I do?

### ISSUE THREAD

**Issue by ghost** [Him188/MyMap#9]
Look title

**Comment by Him188** [comment]
Please use /mymap del <id>

**Comment by ghost** [comment]
I mean, if I try to /mymap add 1, then I have to create a rectangle using item frames (break them). But I can't break these Item Frames

**Comment by Him188** [comment]
You can firstly create a rectangle using other blocks, like STONE.
Then /mymap add 1
Then the rectangle will be replaced with frames.

The frames that were automatically placed by the plugin cannot be removed.
You can use /mymap remove 1, then you can break the block frames.

**Comment by ghost** [comment]
ok, i'll try

**Comment by ghost** [comment]
thx, works
